const express = require("express");
const cors = require("cors");
const app = express();
require("./config/mongoose.config");
app.use(cors());
const port = 8000;
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
require("./routes/person.route")(app);
app.listen(port, () => console.log(`Listening on port: ${port}`));
